### ISSUE TITLE
Insta-BF python error

### ISSUE THREAD

**Issue by AgentP5547** [samsesh/SocialBox-Termux#103]
When I try run this command "python insta-bf.py"
I get this following error:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/SocialBox-Termux/insta-bf/instabf.py", line 3, in <module>                                     import requests, sys, threading, time, os, random                                     File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/__init__.py", line 43, in <module>                        import urllib3                            File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (             File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (                  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/data/data/com.termux/files/usr/lib/python3.11/collections/__init__.py)

I ran this on termux  please help

**Comment by seveservices** [comment]
> I ran this on termux please help

You can dm [seve.services](https://www.instagram.com/seve.services) on instagram and we will help you out
